version: '3'
services:
  camouflage-backend:
    build: 
      context: .
      dockerfile: backend.dockerfile
    environment:
      PORT: 8080
      ADDRESS: 0.0.0.0
    ports:
      - 8080:8080
  camouflage-frontend:
    build: 
      context: .
      dockerfile: frontend.dockerfile
    environment:
      PORT: 8501
      ADDRESS: 0.0.0.0
    ports:
      - 8501:8501
    links:
      - camouflage-backend